### ISSUE TITLE
pip install errors

### ISSUE THREAD

**Issue by tazomatalax** [arankwende/ipmi-mqtt#3]
Hi again,

Tried running on my Pi4 and got this when installing modules

```
pi@octopi:~/ipmi/ipmi-mqtt $ sudo pip install yaml paho-mqtt python-daemon
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting yaml
  Could not find a version that satisfies the requirement yaml (from versions: )
No matching distribution found for yaml
```
How can I get around this? 

Also, great stuff making this, I just really want it to work!

**Comment by tazomatalax** [comment]
followed the dockerfile install instructions 
`pip install pyyaml paho-mqtt python-daemon`

and managed to get to running the script but hit another snag and cant figure out why

```
  File "./ipmi-mqtt.py", line 23
    logging.info(f"Opening the following file: {config_file}")
                                                            ^
SyntaxError: invalid syntax
```
pointing to the " as the invalid syntax.

**Comment by arankwende** [comment]
I'll look at it this weekend and get back to you!

**Comment by arankwende** [comment]
> Hi again,
> 
> Tried running on my Pi4 and got this when installing modules
> 
> ```
> pi@octopi:~/ipmi/ipmi-mqtt $ sudo pip install yaml paho-mqtt python-daemon
> Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
> Collecting yaml
>   Could not find a version that satisfies the requirement yaml (from versions: )
> No matching distribution found for yaml
> ```
> How can I get around this? 
> 
> Also, great stuff making this, I just really want it to work!
> 
> 

It should be pyyaml not yaml, I'll change it in the instructions.

**Comment by arankwende** [comment]
> followed the dockerfile install instructions 
> `pip install pyyaml paho-mqtt python-daemon`
> 
> and managed to get to running the script but hit another snag and cant figure out why
> 
> ```
>   File "./ipmi-mqtt.py", line 23
>     logging.info(f"Opening the following file: {config_file}")
>                                                             ^
> SyntaxError: invalid syntax
> ```
> pointing to the " as the invalid syntax.

Was the log file created? Is the /config folder writeable by the program?

**Comment by tazomatalax** [comment]
No log file created and config file and file all same permissions as the script and everything else that came from the git clone.

**Comment by arankwende** [comment]
Ok, I made a modification in case it had something to do with the backlashes and how they're handled by different OSs.
Can you re clone and try it again?

**Comment by arankwende** [comment]
So, I just installed it in an Rpi3 which I had with octoprint(which is also based on octopi) and tested it with your config file (which wasn't gonna work but wanted to make sure it read it), it created the log file and ran as expected (letting me know that it couldn't find the server d'uh :)). Could you check again if it gives you the same error?

**Comment by arankwende** [comment]
> No log file created and config file and file all same permissions as the script and everything else that came from the git clone.

Tazo, did you manage to fix this?

**Comment by tazomatalax** [comment]
A had a go but never managed to get it working. Sorry. I'm still learning. I mainly wanted it for power control but ended up just writing an script for hass container to ssh into host pi and run the ipmitools power down command.
Since then I have moved server to a new location with cheap power and no longer have control from my rpi. Thanks for the assistance anyway!

Tasman.
________________________________

**Comment by arankwende** [comment]
Cool, no problem!
